language: rust
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
    - rust: nightly
  fast_finish: true
  include:
    - rust: nightly-2019-08-13
      before_script:
        - rustup component add rustfmt clippy
      script:
        - cargo build --verbose
        - cargo test --verbose
        - cargo fmt -- --unstable-features --check
        - cargo clippy -- -D clippy
notifications:
  email: false
