language: rust
sudo: false
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: nightly-2018-07-13
      before_script:
        - rustup component add rustfmt-preview clippy-preview
      script:
        - cargo build --verbose
        - cargo test --verbose
        - cargo fmt -- --unstable-features --check
        - cargo clippy -- -D clippy
notifications:
  email: false
