language: rust
sudo: false
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: nightly-2018-05-13
      env: # use env so updating versions causes cache invalidation
        - CLIPPY_VERSION=0.0.199
      before_script:
        - rustup component add rustfmt-preview
        - cargo install clippy --version $CLIPPY_VERSION || echo "clippy already installed"
      script:
        - cargo fmt -- --write-mode=diff
        - cargo clippy -- -D clippy
notifications:
  email: false
