[package]
name = "rps-rust"
version = "0.1.0"
authors = ["Mathias Karlgren"]

[dependencies]
rand = "0.5.4"
strum = "0.10.0"
strum_macros = "0.10.0"

[profile.release]
opt-level = 2
lto = true
debug = false
panic = "abort"
