[package]
name = "rps-rust"
version = "0.1.0"
authors = ["Mathias Karlgren"]

[dependencies]
rand = "0.4.2"
rand_derive = "0.3.1"
strum = "0.9.0"
strum_macros = "0.9.0"

[profile.release]
opt-level = 2
lto = true
debug = false
panic = "abort"
