cargo-features = ["edition"]

[package]
name = "rps-rust"
version = "0.1.0"
authors = ["Mathias Karlgren"]
edition = "2018"

[dependencies]
rand = "0.5"

[profile.release]
opt-level = 2
lto = true
debug = false
panic = "abort"
