[package]
name = "rps-rust"
version = "0.1.0"
authors = ["Mathias Karlgren"]
edition = "2021"

[dependencies]
rand = "0.8"
strum = { version = "0.24", features = ["derive"] }

[profile.release]
lto = true
strip = "debuginfo"
