name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2022-11-19
    - uses: taiki-e/install-action@nextest
    - uses: Swatinem/rust-cache@v2
      with:
        key: nightly-2022-11-19

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run nextest
      run: cargo nextest run

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2022-11-19
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          key: nightly-2022-11-19

      - name: Lint (clippy)
        run: cargo clippy --all-features
      - name: Lint (rustfmt)
        run: cargo fmt --check
